language: php
dist: trusty
cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.cache/composer/files
matrix:
  include:
    - php: 5.6
    - php: 7.3
  fast_finish: true
before_script:
  - composer install
  - cp src/config.php.dist src/config.php
  - git remote set-branches --add origin master
  - git fetch
script:
  - composer check
